function [faces,m]=solvedCube
% function [faces,mapOfFaceIndeces]=rubiks.solvedCube
%
% Return a solved cube face order
%
% Outputs
% faces - a cell array describing the color of each face
% map - a mapping structure that links eace face to a color
%
% See exampleTwists for how this is used


%set color definitions
[y,o,g,b,r,w]=rubiks.colorDefs;

     faces={
       %Yellow face
       {y,y,y;...
 	    y,y,y;...
 	    y,y,y},...
       %Green face
 	   {g,g,g;...
 	    g,g,g;...
 	    g,g,g},...
       %White face
 	   {w,w,w;...
 	    w,w,w;...
 	    w,w,w},...
 	   %Blue face
 	   {b,b,b;...
 	    b,b,b;...
 	    b,b,b},...
       %Red face
 	   {r,r,r;...
 	    r,r,r;...
 	    r,r,r},...
 	   %Orange face
 	   {o,o,o;...
 	    o,o,o;...
 	    o,o,o}
    };


%make a "map" to more easily call faces
m.y=1;
m.g=2;
m.w=3;
m.b=4;
m.r=5;
m.o=6;